language: java
jdk:
- oraclejdk8
script: mvn clean install

deploy:
  provider: heroku
  api_key:
    secure: UwCsEXFvw/21aADp6qcMjkF9j0CVz7sJApr9V1Mv/2mwsVZHDErIL8+sPC8Z8Ujj83zgP1o82ERq19jfIU4nuTOfzxOATy007HlB3LGKb6JFq/I5o9+nvBHXXtXci1lCRSJqpd5V+qiOFxI0D2cBLknReZcfjeG8Lecc6rh3Fw8m7vX0+q8SxsQPeTqA+RwG5/AG6eWOljPogO4oUMYdEdgaUqVxhr8Wv63VGUYYRcXZUvn27ikRnvhH+9ctFnObQo8sqnZg8eXD+WQJAn9PVhtlNR1tipYqHan4a7xUJ8ARGw3ugWaJyGjV+OC43Sgi4MhU0G+kVyV37FM9IoyDVdur3EqX2wcp8BuEHlYgWOrk6b7wgVIRk7jwotQHV09NcrglIJ0knPb22xbrJ3wfB4TWoWU2YGSnOMhH2LEdrAtx1Qh4HacEKRF+dkwWexz0F7eey/TS6KW1g8osdR+gVngEZ/NGUXVgz3tDWc9cn/1vEealD+ZeKM0ROHAcQ1RzDNPJ0y4OBeLSzNvS9pFD3SUdR5uMtciAXvRATQOUwfB4ZmdMTetBQNYRmXoQAxXm3hm4veu+ssQoyueLbv14gZ+N1F6fTF5fdzkRuv8STgtOeJ+R8W4Rn0KhBQi0m66ZUmRWEx3HbmYeV/XCtsOQY6Mc/xSdFqJyBYOosl3TC9Q=
  app: ayhan-interview-example
  on:
    repo: ayhanugurlu/interview-example
    
